import type { Locale, Templates } from "./types";

const en = {
  community: "TANDAU / COMMUNITY", providersTitle: "Good people. Great gatherings.",
  providersIntro: "Meet independent event professionals, explore their services, and bring your team together.",
  providers: "Find a provider", events: "My events", account: "My account", signIn: "Sign in", signUp: "Create account", signOut: "Sign out",
  publicNote: "Community listings are published by members and have not been verified by Tandau. Prices are starting estimates; agree on scope and availability directly.",
  separateCatalog: "Community listings are separate from the supplied matching catalog. Catalog profiles do not imply registered accounts.",
  category: "Service", city: "City", allCities: "All cities", allServices: "All services", search: "Search by name or service", searchPlaceholder: "A name, a detail, an idea…",
  priceHint: "1–100,000,000 KZT, whole numbers. Grouping spaces are welcome: 150 000.", priceInvalid: "Enter a whole price from 1 to 100,000,000. Letters, signs and exponents are not accepted; check your input or paste again.",
  results: "listings", clearFilters: "Clear filters", unverified: "Community · unverified", from: "From", noListings: "Room for the first introduction.",
  noListingsBody: "No listings match these filters yet. Try another city or service, or publish your own.", publish: "Publish a service", planEvent: "Plan an event", inviteHint: "Create an event to invite providers to a specific service slot.",
  loading: "Loading…", sessionLoading: "Checking your session…", retry: "Try again", cancel: "Cancel", save: "Save changes", saving: "Saving…", edit: "Edit", back: "Back to events",
  accountTitle: "Your place in the community.", accountIntro: "One simple account to plan together or share what you do.", noEmail: "No email needed. Choose a username and password to try Tandau.",
  username: "Username", usernameHint: "3–32 letters (A–Z), numbers, underscores, dots or hyphens.", displayName: "Display name", password: "Password", passwordHint: "10–128 characters. Use a password you do not use elsewhere.",
  chooseRole: "How will you use Tandau?", organizer: "Organizer", provider: "Service provider", organizerHint: "Build a plan and invite your team.", providerHint: "Publish services and respond to invitations.",
  welcome: "Welcome", signedAs: "Signed in as", dashboard: "Your services", dashboardIntro: "Share your starting price and what is included. Only you can edit these listings.", newListing: "New listing", editListing: "Edit listing", listingTitle: "Service title", price: "Starting price · KZT", description: "About this service", descriptionHint: "20–2,000 characters. Include what you offer and what affects the final price.",
  active: "Visible in the public directory", visible: "Published", hidden: "Hidden", noOwnListings: "Your next client starts with a hello.", noOwnListingsBody: "Publish your first service so organizers can discover and invite you.", listingSaved: "Your listing is saved.", listingEditWarning: "Uncheck visibility to withdraw this listing. Editing or withdrawing a listing asks providers to reconfirm any previously accepted invitations for it.", directoryLimit: "Showing up to 200 listings. Use city and service filters to narrow your search.",
  eventsTitle: "Bring the whole team together.", eventsIntro: "Start with a template, make the plan yours, and invite the right people for every detail.",
  coordinationNote: "This is a coordination plan. Accepting an invitation confirms participation in the current plan and service offer; it is not a booking, payment, or guarantee of availability.",
  offerDetails: "Review service details", replaceInviteWarning: "Replacing an invitation requests a new confirmation for this service. Other providers keep their existing confirmations.",
  gateTitle: "A shared plan starts with an account.", gateBody: "Sign in to create events, answer invitations and join private team conversations. Browsing providers is open to everyone.",
  newEvent: "Create an event", eventTitle: "Event name", date: "Event date", dateHint: "Choose a date between 2026 and 2035.", template: "Start with a template", templateHint: "You can change services and tasks after creating your plan.", create: "Create plan", noEvents: "Every great event begins with a plan.", noEventsBody: "Create your first event here. Invitations sent to you will appear here too.", yourEvent: "You organize", invitedEvent: "You’re on the invite list", owner: "Organizer", openEvent: "Open plan",
  teamReady: "All providers confirmed", teamPending: "Team still coming together", readinessHint: "Every service slot needs an accepted invitation for the current plan and offer.", confirmed: "confirmed", of: "of", version: "Plan & offer revision", noSlots: "Add a service to start building your team.", plan: "Service plan", team: "Team & invitations", chat: "Private team chat",
  editPlan: "Edit plan", savePlan: "Save plan & request confirmation", resetWarning: "Changing services, notes or task text asks accepted providers to confirm again. Chat is available only while a provider has an accepted invitation for the current plan. Removing a service or changing its category removes its invitation.", progressOnly: "Checking off tasks updates progress and keeps existing confirmations.", progressSaved: "Progress saved. Existing confirmations are unchanged.",
  addService: "Add service", removeService: "Remove service", notes: "Service notes", notesPlaceholder: "Timing, style, quantities, or anything your provider should know…", tasks: "Checklist", addTask: "Add task", removeTask: "Remove task", taskText: "Task", completeTask: "Mark task complete", noTasks: "No tasks yet.", unsaved: "You have unsaved plan changes.", changedElsewhere: "The plan or a service offer changed while you were editing. Your draft is kept. Review the latest revision before saving.", discard: "Discard draft & load latest", planSaved: "Plan saved. Providers need to confirm this version.",
  inviteProvider: "Invite a provider", chooseProvider: "Choose a provider", noCandidates: "No active community listings match this service and city yet.", selectProvider: "Select a matching listing", sendInvite: "Send invitation", replaceInvite: "Replace invitation", noInvite: "No provider invited", invited: "Invited · awaiting reply", accepted: "Accepted", declined: "Declined", accept: "Accept this plan", decline: "Decline invitation", leave: "Leave this plan", invitationForYou: "Your invitation", reconfirm: "Review the current plan, starting price and service details before accepting to join the chat.", currentVersion: "Current plan", oldVersion: "Needs reconfirmation", inviteSaved: "Invitation sent.", responseSaved: "Your response is saved.", saveBeforeInvite: "Save or discard your draft before changing invitations.",
  chatHint: "Only the organizer and providers who accepted the current plan can read and send messages.", chatLocked: "Accept an invitation to join the private chat.", chatEmpty: "Start the conversation. A quick hello goes a long way.", message: "Message", messagePlaceholder: "Discuss the details with your team…", send: "Send message", latestMessages: "Showing up to the latest 100 messages.",
  networkError: "We couldn’t reach the community service. Check your connection and try again.", genericError: "That didn’t go through. Please try again.", validationError: "Check the form fields and their limits, then try again.", credentialsError: "The username or password is incorrect.", usernameTaken: "That username is already taken. Try another one.", authError: "Your session has ended. Sign in again to continue.", permissionError: "Your account no longer has access to this action.", conflictError: "This plan has changed. Load the latest version and review it before trying again.", missingError: "This item is no longer available.", rateError: "Too many attempts. Please wait a moment and try again.", listingError: "This listing is no longer available or does not match the service and city.", logoutError: "Private data has been cleared from this screen, but sign-out could not be confirmed. Retry to close the server session.", retryLogout: "Retry sign out", templatesError: "Templates could not be loaded. Try again to enable creation and filters.", sessionError: "We couldn’t check your session. Public listings are still available.", listingLimit: "You can have up to 20 listings. Edit an existing service to update your offer.", eventLimit: "You have reached the limit of 50 events for this account.", providerRequired: "Publishing services requires a provider account.", ownerRequired: "Only the owner can change this item.", originError: "This request could not be verified. Open Tandau in its original tab and try again.", formatError: "The request could not be read. Reload the page and try again.", storageError: "Community storage is temporarily unavailable. Please try again shortly.",
};

const ru: Record<keyof typeof en, string> = {
  community: "TANDAU / СООБЩЕСТВО", providersTitle: "Свои люди. Особенные события.",
  providersIntro: "Знакомьтесь со специалистами, выбирайте услуги и собирайте команду для вашего события.",
  providers: "Найти специалиста", events: "Мои события", account: "Мой аккаунт", signIn: "Войти", signUp: "Создать аккаунт", signOut: "Выйти",
  publicNote: "Объявления публикуют участники сообщества; Tandau их не проверял. Указана начальная цена. Объём работ и свободные даты уточняйте у специалиста.",
  separateCatalog: "Объявления сообщества не попадают в исходный каталог подбора. Профили из каталога не означают наличие аккаунтов.",
  category: "Услуга", city: "Город", allCities: "Все города", allServices: "Все услуги", search: "Поиск по имени или услуге", searchPlaceholder: "Имя, деталь, идея…",
  priceHint: "От 1 до 100 000 000 ₸, целое число. Можно разделять тысячи пробелами: 150 000.", priceInvalid: "Введите целую цену от 1 до 100 000 000. Буквы, знаки и экспоненты недопустимы; исправьте значение или вставьте его заново.",
  results: "объявлений", clearFilters: "Сбросить фильтры", unverified: "Сообщество · не проверено", from: "От", noListings: "Место для первого знакомства.",
  noListingsBody: "По этим фильтрам пока нет объявлений. Попробуйте другой город или услугу — или расскажите о себе.", publish: "Предложить услугу", planEvent: "Спланировать событие", inviteHint: "Создайте событие, чтобы пригласить специалистов на конкретные услуги.",
  loading: "Загружаем…", sessionLoading: "Проверяем сессию…", retry: "Повторить", cancel: "Отмена", save: "Сохранить изменения", saving: "Сохраняем…", edit: "Изменить", back: "К списку событий",
  accountTitle: "Ваше место в сообществе.", accountIntro: "Простой аккаунт, чтобы планировать вместе или рассказать о своём деле.", noEmail: "Почта не нужна. Придумайте логин и пароль, чтобы попробовать Tandau.",
  username: "Логин", usernameHint: "3–32 латинские буквы, цифры, знаки подчёркивания, точки или дефисы.", displayName: "Ваше имя", password: "Пароль", passwordHint: "10–128 символов. Используйте пароль, который не применяете на других сайтах.",
  chooseRole: "Как вы будете пользоваться Tandau?", organizer: "Организатор", provider: "Специалист", organizerHint: "Создавайте план и приглашайте команду.", providerHint: "Публикуйте услуги и отвечайте на приглашения.",
  welcome: "Добро пожаловать", signedAs: "Вы вошли как", dashboard: "Ваши услуги", dashboardIntro: "Расскажите, что входит в услугу, и укажите начальную цену. Редактировать объявления можете только вы.", newListing: "Новое объявление", editListing: "Редактировать объявление", listingTitle: "Название услуги", price: "Начальная цена · ₸", description: "Об услуге", descriptionHint: "20–2 000 символов. Что вы предлагаете и от чего зависит итоговая цена?",
  active: "Показывать в открытом каталоге", visible: "Опубликовано", hidden: "Скрыто", noOwnListings: "Всё начинается со знакомства.", noOwnListingsBody: "Опубликуйте первую услугу, чтобы организаторы могли найти и пригласить вас.", listingSaved: "Объявление сохранено.", listingEditWarning: "Снимите отметку видимости, чтобы убрать объявление из каталога. Изменение или скрытие объявления требует повторного подтверждения ранее принятых приглашений к этой услуге.", directoryLimit: "Показано до 200 объявлений. Уточните город и услугу, чтобы сузить поиск.",
  eventsTitle: "Соберите команду вашего события.", eventsIntro: "Выберите шаблон, добавьте детали и пригласите нужных людей для каждой задачи.",
  coordinationNote: "Это план совместной работы. Принятие приглашения подтверждает участие с текущим планом и предложением услуги, а не бронирование, оплату или гарантию свободной даты.",
  offerDetails: "Посмотреть условия услуги", replaceInviteWarning: "Замена приглашения требует нового подтверждения для этой услуги. Подтверждения остальных специалистов сохраняются.",
  gateTitle: "Общий план начинается с аккаунта.", gateBody: "Войдите, чтобы создавать события, отвечать на приглашения и общаться с командой. Смотреть объявления можно без входа.",
  newEvent: "Создать событие", eventTitle: "Название события", date: "Дата события", dateHint: "Выберите дату с 2026 по 2035 год.", template: "Начните с шаблона", templateHint: "После создания плана можно менять услуги и задачи.", create: "Создать план", noEvents: "Большое событие начинается с плана.", noEventsBody: "Создайте здесь первое событие. Приглашения для вас тоже появятся здесь.", yourEvent: "Вы организуете", invitedEvent: "Вы в списке приглашённых", owner: "Организатор", openEvent: "Открыть план",
  teamReady: "Все специалисты подтвердили участие", teamPending: "Команда ещё собирается", readinessHint: "Для каждой услуги нужно принятое приглашение к текущему плану и предложению.", confirmed: "подтверждено", of: "из", version: "Версия плана и предложений", noSlots: "Добавьте услугу, чтобы начать собирать команду.", plan: "План услуг", team: "Команда и приглашения", chat: "Личный чат команды",
  editPlan: "Редактировать план", savePlan: "Сохранить и запросить подтверждение", resetWarning: "Изменение услуг, деталей или текста задач требует повторного согласия от принявших приглашение специалистов. Чат доступен, пока у специалиста есть принятое приглашение к текущему плану. Удаление услуги или смена её категории удалит приглашение.", progressOnly: "Отметки о выполнении задач обновляют прогресс и сохраняют подтверждения участников.", progressSaved: "Прогресс сохранён. Подтверждения участников не изменились.",
  addService: "Добавить услугу", removeService: "Удалить услугу", notes: "Детали услуги", notesPlaceholder: "Время, стиль, количество и всё, что стоит знать специалисту…", tasks: "Список задач", addTask: "Добавить задачу", removeTask: "Удалить задачу", taskText: "Задача", completeTask: "Отметить задачу выполненной", noTasks: "Задач пока нет.", unsaved: "В плане есть несохранённые изменения.", changedElsewhere: "Пока вы редактировали, план или предложение услуги изменились. Ваш черновик сохранён на экране. Проверьте актуальную версию перед сохранением.", discard: "Отменить правки и загрузить актуальный план", planSaved: "План сохранён. Специалистам нужно подтвердить новую версию.",
  inviteProvider: "Пригласить специалиста", chooseProvider: "Выбрать специалиста", noCandidates: "Пока нет активных объявлений для этой услуги в выбранном городе.", selectProvider: "Выберите подходящее объявление", sendInvite: "Отправить приглашение", replaceInvite: "Заменить приглашение", noInvite: "Специалист не приглашён", invited: "Приглашён · ждём ответа", accepted: "Принято", declined: "Отклонено", accept: "Принять этот план", decline: "Отклонить приглашение", leave: "Покинуть этот план", invitationForYou: "Ваше приглашение", reconfirm: "Проверьте текущий план, начальную цену и условия услуги перед принятием приглашения и входом в чат.", currentVersion: "Текущий план", oldVersion: "Нужно подтвердить заново", inviteSaved: "Приглашение отправлено.", responseSaved: "Ваш ответ сохранён.", saveBeforeInvite: "Сохраните или отмените правки перед изменением приглашений.",
  chatHint: "Читать и отправлять сообщения могут организатор и специалисты, принявшие текущий план.", chatLocked: "Примите приглашение, чтобы присоединиться к личному чату.", chatEmpty: "Начните разговор. Простое «привет» помогает познакомиться.", message: "Сообщение", messagePlaceholder: "Обсудите детали с командой…", send: "Отправить", latestMessages: "Показаны последние сообщения — не более 100.",
  networkError: "Не удалось связаться с сообществом. Проверьте соединение и повторите попытку.", genericError: "Не получилось выполнить действие. Попробуйте ещё раз.", validationError: "Проверьте поля формы и ограничения, затем повторите попытку.", credentialsError: "Неверный логин или пароль.", usernameTaken: "Этот логин уже занят. Попробуйте другой.", authError: "Сессия завершилась. Войдите снова, чтобы продолжить.", permissionError: "У вашего аккаунта больше нет доступа к этому действию.", conflictError: "План изменился. Загрузите актуальную версию и проверьте её перед повторной попыткой.", missingError: "Этот объект больше недоступен.", rateError: "Слишком много попыток. Подождите немного и попробуйте снова.", listingError: "Объявление больше недоступно или не подходит по услуге и городу.", logoutError: "Личные данные убраны с экрана, но выход на сервере не подтверждён. Повторите выход, чтобы закрыть сессию.", retryLogout: "Повторить выход", templatesError: "Не удалось загрузить шаблоны. Повторите попытку, чтобы создавать планы и пользоваться фильтрами.", sessionError: "Не удалось проверить сессию. Открытые объявления по-прежнему доступны.", listingLimit: "Можно создать до 20 объявлений. Обновите существующую услугу.", eventLimit: "Достигнут лимит в 50 событий для этого аккаунта.", providerRequired: "Публиковать услуги можно только из аккаунта специалиста.", ownerRequired: "Изменить этот объект может только его владелец.", originError: "Не удалось проверить запрос. Откройте исходную вкладку Tandau и попробуйте снова.", formatError: "Не удалось прочитать запрос. Обновите страницу и повторите попытку.", storageError: "Хранилище сообщества временно недоступно. Попробуйте немного позже.",
};
export const copy = { ru, en };
export type Copy = typeof en;
export const cityLabel = (city: string, locale: Locale) => locale === "ru" ? city : ({ Алматы: "Almaty", Астана: "Astana", Зарубежье: "Abroad" }[city] ?? city);
export const serviceLabel = (category: string, templates: Templates | null, locale: Locale) => templates?.services.find(s => s.category === category)?.label[locale] ?? category;
export const money = (amount: number, locale: Locale) => `${new Intl.NumberFormat(locale === "ru" ? "ru-RU" : "en-GB").format(amount)} ₸`;
export function eventDate(date: string, locale: Locale) {
  return new Intl.DateTimeFormat(locale === "ru" ? "ru-RU" : "en-GB", { day: "numeric", month: "long", year: "numeric", timeZone: "UTC" }).format(new Date(`${date}T12:00:00Z`));
}
