import { MAX_DURATION_HOURS } from "./formNumbers";
import type { Locale } from "./i18n";

export const journeyCopy = {
  ru: {
    home: "Главная", match: "Подбор", skip: "К содержимому",
    eyebrow: "TANDAU · МЕРОПРИЯТИЯ БЕЗ ЛИШНЕГО ПОИСКА",
    title: "Ваше событие.", accent: "Подходящие люди.",
    intro: "Ведущий, фотограф или площадка? Начните с условий — получите короткий список с понятным объяснением, почему подходит каждый.",
    start: "Начать подбор", learn: "Как это работает", small: "Без регистрации · До трёх вариантов · С объяснением выбора",
    note: "Прототип на обезличенном каталоге. Не сервис бронирования.",
    visualLabel: "Принцип подбора, не реальный результат", visualTitle: "Не просто список. Обоснованный выбор.",
    visualChecks: ["Свободен на вашу дату по календарю", "Стартовая цена в рамках бюджета", "Подходит под формат и условия"], visualFoot: "Факты из профиля, а не рекламные обещания.",
    howTitle: "От идеи до короткого списка", howIntro: "Меньше случайных вариантов. Больше понятных решений.",
    steps: [["Расскажите о событии", "Выберите город, дату, формат, категорию и бюджет на одного подрядчика. Язык и длительность — по желанию."], ["Сравните подходящих", "Изучите до трёх вариантов, причины выбора и цитаты из профиля. Занятые и неподходящие не попадут в список."], ["Подготовьте обращение", "Скопируйте запрос из карточки. После получения проверенного контакта уточните доступность и окончательную цену."]],
    categories: "Кто нужен вашему событию?", categoriesIntro: "Выберите категорию и уточните условия. Наличие категории в каталоге не гарантирует вариант в каждом городе.", categoryHint: "Открыть подбор →", categoriesOffline: "Категории появятся после загрузки каталога. Форму можно открыть кнопкой выше.",
    trustTitle: "Честный ответ — даже если вариантов нет", trustBody: "Мы не заполняем список неподходящими профилями. Если категория отсутствует или все заняты, вы увидите причину. Проверенные альтернативы изменят только одно условие — и только с вашего согласия.",
    faqTitle: "Перед началом", faq: [["Это подтверждённая бронь?", "Нет. Свободная дата относится к предоставленному календарю за 23 сентября — 31 декабря 2026 года. Уточните актуальную доступность и итоговую цену перед договорённостью."], ["Почему иногда меньше трёх вариантов?", "Показываем только тех, кто проходит все условия. Календарь, бюджет, формат, язык и длительность не ослабляются ради красивого списка."], ["Можно связаться с подрядчиком?", "В каждой карточке есть текст обращения для копирования. Исходный каталог обезличен и не содержит проверенных телефонов или email. Ничего не отправляется автоматически."], ["Что означают пометки в карточках?", "В каталоге есть синтетические профили и восстановленные значения цены или города. Мы сохраняем эти пометки: данные из примера не равны внешней проверке."]],
    bottomTitle: "Начнём с вашего события?", bottomText: "Пять основных параметров. Обоснованный короткий список.", footer: "Tandau · HackAlem 2026 · Обезличенный демонстрационный каталог",
    formTitle: "Расскажите о событии", formIntro: "Пять условий — и мы покажем только подходящих подрядчиков.", formFooterTitle: "До трёх обоснованных вариантов", footerNav: "Навигация в подвале", footerNote: "Прототип для подбора подрядчиков. Наличие и финальную стоимость подтверждайте напрямую.",
    contact: "Связаться / подготовить запрос", contactNotice: "В обезличенном каталоге нет проверенных телефонов и email. Это черновик: скопируйте его и отправьте самостоятельно, когда получите подтверждённый контакт. Приложение ничего не отправляет и не бронирует.", draft: "Текст обращения", copy: "Скопировать запрос", copied: "Скопировано. Сообщение не отправлено.", manual: "Не удалось скопировать автоматически. Текст выделен — скопируйте его вручную.",
    budgetHint: "Целая сумма без пробелов, например 3000000. Бюджет на одного подрядчика.", durationHint: `Больше 0 и не более ${MAX_DURATION_HOURS} часов; например 6 или 6,5. Буквы и экспоненты не принимаются.`,
  },
  en: {
    home: "Home", match: "Find a match", skip: "Skip to content",
    eyebrow: "TANDAU · LESS SEARCHING, MORE CELEBRATING",
    title: "Your occasion.", accent: "The right people.",
    intro: "A host, a photographer or a venue? Start with your requirements and get a shortlist with a clear explanation of why each option fits.",
    start: "Start matching", learn: "How it works", small: "No signup · Up to three options · Reasons included",
    note: "An anonymized catalog prototype. Not a booking service.",
    visualLabel: "Matching principles, not an actual result", visualTitle: "Not just a list. A reason to choose.",
    visualChecks: ["Free on your date in the supplied calendar", "Starting price within your budget", "Fits your event and requirements"], visualFoot: "Profile facts, not advertising promises.",
    howTitle: "From an idea to a shortlist", howIntro: "Fewer irrelevant options. More informed decisions.",
    steps: [["Tell us about your event", "Choose a city, date, format, category and budget per contractor. Language and duration are optional."], ["Compare eligible options", "Review up to three matches, their reasons and source quotes. Booked or unsuitable profiles stay out of the list."], ["Prepare your inquiry", "Copy the inquiry from a card. Once you obtain a verified contact, confirm availability and the final quote directly."]],
    categories: "Who does your event need?", categoriesIntro: "Choose a category, then refine your requirements. A catalog category does not guarantee availability in every city.", categoryHint: "Set your requirements →", categoriesOffline: "Categories will appear when the catalog loads. You can still open the form above.",
    trustTitle: "An honest answer, even when nobody fits", trustBody: "We never pad a shortlist with unsuitable profiles. If a category is missing or everyone is booked, we explain why. Verified alternatives change just one condition, and only after you choose one.",
    faqTitle: "Before you begin", faq: [["Is this a confirmed booking?", "No. Availability comes from a supplied calendar covering 23 September–31 December 2026. Confirm current availability and the final quote before making an agreement."], ["Why are there sometimes fewer than three options?", "Only profiles meeting every condition qualify. We do not relax calendar, budget, format, language or duration requirements to fill the list."], ["Can I contact a contractor?", "Each card has a copyable inquiry. The source catalog is anonymized and has no verified phone numbers or emails. Nothing is sent automatically."], ["What do the notes on cards mean?", "The catalog includes synthetic profiles and imputed prices or cities. We preserve these labels: supplied example data is not independent verification."]],
    bottomTitle: "Let's start with your occasion.", bottomText: "Five key requirements. One explained shortlist.", footer: "Tandau · HackAlem 2026 · Anonymized demonstration catalog",
    formTitle: "Tell us about your event", formIntro: "Five requirements, then only eligible contractors appear.", formFooterTitle: "Up to three explained options", footerNav: "Footer navigation", footerNote: "A contractor-matching prototype. Confirm availability and final pricing directly.",
    contact: "Contact / prepare inquiry", contactNotice: "This anonymized catalog contains no verified phone numbers or emails. This is a draft: copy it and send it yourself once you obtain a verified contact. The app does not send messages or make bookings.", draft: "Inquiry draft", copy: "Copy inquiry", copied: "Copied. No message was sent.", manual: "Automatic copying failed. The text is selected; please copy it manually.",
    budgetHint: "Whole KZT without spaces, for example 3000000. Budget per contractor.", durationHint: `Greater than 0 and up to ${MAX_DURATION_HOURS} hours inclusive, such as 6 or 6.5. Letters and exponents are not accepted.`,
  },
} satisfies Record<Locale, object>;
